// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlqt9crrTjdOQ-Lqw2tsDtURw5_LxRpjo',
    appId: '1:906028719271:web:0cb8374582a6db47e24f82',
    messagingSenderId: '906028719271',
    projectId: 'project-18d89',
    authDomain: 'project-18d89.firebaseapp.com',
    storageBucket: 'project-18d89.firebasestorage.app',
    measurementId: 'G-WVW70KEF0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzsH1kmSRNeC5tvsNPtEfQr_NdF8XKFOU',
    appId: '1:906028719271:android:6ef3c9c64941bf82e24f82',
    messagingSenderId: '906028719271',
    projectId: 'project-18d89',
    storageBucket: 'project-18d89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX7WbSs_i-Pgm720B1A9-Hw9HAeC1S1PU',
    appId: '1:906028719271:ios:1fc9c0981fcf63a0e24f82',
    messagingSenderId: '906028719271',
    projectId: 'project-18d89',
    storageBucket: 'project-18d89.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX7WbSs_i-Pgm720B1A9-Hw9HAeC1S1PU',
    appId: '1:906028719271:ios:1fc9c0981fcf63a0e24f82',
    messagingSenderId: '906028719271',
    projectId: 'project-18d89',
    storageBucket: 'project-18d89.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlqt9crrTjdOQ-Lqw2tsDtURw5_LxRpjo',
    appId: '1:906028719271:web:c3c85600e4edf7b7e24f82',
    messagingSenderId: '906028719271',
    projectId: 'project-18d89',
    authDomain: 'project-18d89.firebaseapp.com',
    storageBucket: 'project-18d89.firebasestorage.app',
    measurementId: 'G-RW890CZCJ4',
  );

}